### ISSUE TITLE
Alpha label

### ISSUE THREAD

**Issue by mattheworiordan** [ably-labs/GameRoomSDK#11]
@ikbalkaya I see this repo is alpha.

Could we not use common image labels in the README to provide obvious signposting about the status.  There should be plenty of examples we can lean on across the web. @tbuntel is this not something we can standardise across all Github repos?   See https://github.com/yoshuawuyts/github-standard-labels/blob/master/README.md for example.

**Comment by ikbalkaya** [comment]
@mattheworiordan Sorry for delay on this one. I have quickly created a badge using a tool from https://github.com/badges/shields
I have created a static image here as I don't have much time on this, but I will check later to see if I can see if I can be more dynamic and read / update values from various places.

For standardisation, I can see that we have badges on some of our repositories, however they seem to differ from each other and their location is slightly different on Readme files.
